### ISSUE TITLE
4.8.0 is available

### ISSUE THREAD

**Issue by mavhc** [open-circle-ltd/chocolatey.wazuh-agent#14]
https://packages.wazuh.com/4.x/windows/wazuh-agent-4.8.0-1.msi

**Comment by carlottostromstedt** [comment]
Thanks for the heads up @mavhc! We had a problem with our Github-Actions but that is fixed, and 4.8 is now approved and available on the community repo :)

https://community.chocolatey.org/packages/wazuh-agent
